### ISSUE TITLE
Reassigning phantom counts instead of purguing

### ISSUE THREAD

**Issue by luwaert** [csglab/PhantomPurgeR#3]
Hi, 

Thanks for putting together this great tool and the insights in the 2020 paper. My understanding is that the current version of the workflow purges phantom counts. Would it be possible to instead _reassign_ phantom counts to their most likely cell of origin? 

I am using Drop-seq scRNAseq libraries sequenced on a Novaseq at very high sequencing depth, which have highly degenerate 12 bp cell barcodes and 8 bp UMIs. One could perform a filtering step to only retain cells with a very high number of UMIs (e.g. only retain cells >20,000 UMIs), and once that set of credible real cells is defined, try to reassign phantom counts to their correct real cells. 

Any thoughts in this regard would be greatly appreciated. Thanks again!

**Comment by rfarouni** [comment]
Hi,
Reassignment is done as part of the pipeline. The purging is done on molecules than have low confidence after reassignment. Please see [here](https://github.com/csglab/PhantomPurgeR/blob/48a52fa59ff8f5b2062c65ea1276a53f35e13050/R/4_purge_data.R#L80l). A minimum umi per cell parameter is also [implemented](https://github.com/csglab/PhantomPurgeR/blob/48a52fa59ff8f5b2062c65ea1276a53f35e13050/R/2_join_data.R#L55)

**Comment by luwaert** [comment]
Thanks for the answer and the clarification! This is exactly what I needed. 

I was also wondering about how you think is the best way to use PhantomPurgeR on the output files of other single cell technologies, such as Drop-seq. In your vignettes I see the starting files are molecule_info.h5 files, produced by CellRanger, which are not produced by default in Drop-seq.

**Comment by rfarouni** [comment]
You can write your own function  for loading Drop-seq files. As long as the structure of the list you return is the same as [here](https://github.com/csglab/PhantomPurgeR/blob/48a52fa59ff8f5b2062c65ea1276a53f35e13050/R/1_load_data.R#L62) there shouldn't be a problem
