### ISSUE TITLE
Error When Executing: (3) Estimate sample index hopping rate out <- estimate_hopping_rate(out)

### ISSUE THREAD

**Issue by ckrilow** [csglab/PhantomPurgeR#4]
Hi,

I am running two samples through the pipeline, when I get to (3) Estimate sample index hopping rate I get the following error. I have replicated all the steps in this document (https://csglab.github.io/PhantomPurgeR/assets/notebooks/novaseq_l1_vignette.html) 

> out <- estimate_hopping_rate(out)
Estimating SIHR. Step 1: creating outcome counts datatable: 0.205 sec elapsed
Estimating SIHR. Step 2: creating chimera counts datatable: 0.04 sec elapsed
Estimating SIHR. Step 3: fitting GLM: 0.373 sec elapsed
Estimating SIHR. Step 4: computing summary statistics: 0.129 sec elapsed
Warning message:
Problem with `mutate()` input `confint_tidied`.
ℹ confint_tidy is now deprecated and will be removed from a future release of broom. Please use the applicable confint method.
ℹ Input `confint_tidied` is `map(fit, confint_tidy, conf.level = conf_level)`.

Any ideas?

**Comment by rfarouni** [comment]
Hi,

Thanks for alerting me. It seems that I will need to modify this line of code to use the new confint function before the next release of broom. I am guessing the code runs fine for now, correct?

Rick,

**Comment by ckrilow** [comment]
Hi, Rick,

Thanks alot for getting back to me on this issue. So the code/pipeline works fine up until this point, but then it breaks. I am currently running R 3.6.2, and it wont go past this point. 

Is it possible for you to put this fix in a DEV branch and I can do a pull from that?

**Comment by rfarouni** [comment]
I am not sure if it breaks because of the function. When I run the broom _confint_tidy_, I still get the expected output but with a warning message. Are you running all the samples assigned to the lane? At any rate, if you run this code after you load the package but before you run the pipeline then you can override the broom function and its warning message

```
confint_tidy<- function (x, conf.level = 0.95, func = stats::confint, ...) 
{
    ci <- suppressMessages(func(x, level = conf.level, ...))
    if (is.null(dim(ci))) {
        ci <- matrix(ci, nrow = 1)
    }
    all_na <- apply(ci, 1, function(x) all(is.na(x)))
    ci <- ci[!all_na, , drop = FALSE]
    colnames(ci) <- c("conf.low", "conf.high")
    as_tibble(ci)
}
```

**Comment by ckrilow** [comment]
Hi -  Yes, I am running all the samples (there are two) from the same lane. I will try your fix and let you know, thanks for the reply.

**Comment by ckrilow** [comment]
Hi,

Your fix worked nicely, thanks again for the help and speedy reply to the issue! The plots look great, I hope they will help me figure out our potential index hopping problem. 

Cheers,
-Chad
