### ISSUE TITLE
More cells in every samples after running the pipeline

### ISSUE THREAD

**Issue by andynkili** [csglab/PhantomPurgeR#5]
I have run PhantomPurge on 4 samples (they were sequenced with other samples from other labs).
After running the pipeline, I get Seurat objects with the command:
`sample1_obj<-createSeuratObject(counts = out$umi_count$retained$sample1, min.cells=3, min.features=200 )` and obtain an object with 63,344 cells. 
However, when I use the same command on the raw sample (the one before purging):
`sample1<-CreateSeuratObject(counts = sample1.count, project = 'sample1', min.cells=3, min.features=200 )`, I get an object with 32,496 cells.
I have the same results for the 3 others samples (more cells after running the tools than in the raw data), how come?

Also, if I run the tool only on my for 4 samples (VS including samples from other lab that were sequenced on the same lane), would potential phantom molecules from other lab samples be purged/removed from my 4 samples (if those molecules are molecules that have low confidence after reassignment)?

**Comment by rfarouni** [comment]
Hi,
The createSeuratObject function filters cells based on the min featues threshold. Can you run these commands and share the output?
```
str(out$umi_count$retained$sample1)
str(sample1.count)
```

Thanks

**Comment by andynkili** [comment]
Hi,

Thanks for your quick reply.
I think I figured where the problem came from: the Seurat object I have create is based on the cellranger filtered matrix.
When I create a Seurat object from the cellranger raw  unfiltered matrix, I have 64,340 cells (while the Seurat object made from the purged matrix yielded 63,344 cells, so 4 cells have been reassigned in that sample by PhantomPurge).
And when I check the other samples comparing the PhantomPurge outputs and Seurat objects from raw unfiltered matrix (instead of filtered matrix), the numbers of cells are consistent with one another (PhantomPurge removed some cells and reassigned some).
So the issue, I guess, was that PhantomPurge input (molecule_info.h5) take into account the unfiltered barcodes, right?

**Comment by rfarouni** [comment]
Yes that is correct.
