### ISSUE TITLE
Notebooks No Longer Synchronised WIth R Package Contents

### ISSUE THREAD

**Issue by DarioS** [csglab/PhantomPurgeR#6]
The instruction in workflow_hiseq2500.nb.html is

> **Load Functions**
> ```r
> source(file.path(code_dir, "1_create_joined_counts_table.R"))
> source(file.path(code_dir, "2_create_counts_by_outcome_table.R"))
> source(file.path(code_dir, "3_estimate_sample_index_hopping_rate.R"))
> source(file.path(code_dir, "4_compute_summary_statistics.R"))
> source(file.path(code_dir, "5_reassign_hopped_reads.R"))
> source(file.path(code_dir, "6_purge_phantom_molecules.R"))
> source(file.path(code_dir, "7_call_cells.R"))
> source(file.path(code_dir, "8_summarize_purge.R"))
> source(file.path(code_dir, "9_plotting_functions.R"))```

But, looking at the current state of the package there is 1_load_data.R, 2_join_data.R, 3_estimate_hopping_rate.R, ... Can you please write a new vignette which corresponds to the current version of the code?

**Comment by rfarouni** [comment]
Hi @DarioS,

These workflows are for the analysis done for the paper. The package vignettes are here

https://csglab.github.io/PhantomPurgeR/pages/rpackage.html

Best,
Rick
